# -*- coding: utf-8 -*-
"""Main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qeaCNmfQwXw_KlhVYa9jzNP0zcXRZHTb
"""

# Variabel

a = 2 #integer / bilangan bulat
hewan = "Gajah" # String
#untuk yang dasarnya tidak ada yang namanya Char
b = 'A'  # String
c = True # Boolean
d = False # Boolean
e = 2.0 # Float
f = [] # List / Array
g = {} # Dictionary
h = () # Tuple

# Print

print(hewan)
print("Singa")
print(2)
print(2+3)
print(True)

# Print 2
print("Nama hewannya adalah: " + hewan)
print("Nama hewannya adalah: {}".format(hewan))
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format("Desy", "Medan", "20"))

Nama_Siswa = ["Yulli", "Syahla", "Gia", "Anggita", "Desy"]

print(Nama_Siswa[0])
print(Nama_Siswa[1])
print(Nama_Siswa[2])

Nama_Siswa

List_1 = ["Desy"] * 4
List_1

Nama_Siswa[0:2]

Nama_Siswa[-2]

Nama_Siswa[-3:]

Nama_Siswa.append(1)
Nama_Siswa

Nama = "Desy"
Tempat = "Medan"
Umur = 20
print("Nama : {}, Tempat Tinggal : {}, Umur : {}".format(Nama, Tempat, Umur))


a = ["1","2","3"]
a[-2:]