# -*- coding: utf-8 -*-
"""nilai

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Law-9HXN5ROTeguPzB0jDgikiv1mTuG0
"""

print("Nama : {}, Hobby: {}, cita-cita: {}".format("Desy", "travelling", "business woman"))